{{- if eq .Values.stage "dev" }}
{{- if hasPrefix "www" "TPL_SERVICE" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "TPL_SERVICE.fullname" . }}
  labels:
    {{- include "TPL_SERVICE.labels" . | nindent 4 }}
spec:
  hosts:
  - "api-dev.dein-stall.de"
  gateways:
  - api-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Chart.Name | replace "-service-chart" "" }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "TPL_SERVICE.fullname" . }}
{{- else }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "TPL_SERVICE.fullname" . }}
  labels:
    {{- include "TPL_SERVICE.labels" . | nindent 4 }}
spec:
  hosts:
  - "dev.dein-stall.de"
  gateways:
  - www-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Chart.Name | replace "-service-chart" "" }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "TPL_SERVICE.fullname" . }}
{{- end }}
{{- end }}
