{{- if eq .Values.stage "dev" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "TPL_SERVICE.fullname" . }}
  labels:
    {{- include "TPL_SERVICE.labels" . | nindent 4 }}
spec:
  {{- with .Values.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /{{ .Chart.Name | replace "-service-chart" "" }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "TPL_SERVICE.fullname" . }}
{{- end }}
